name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11.0.11
      uses: actions/setup-java@v1
      with:
        java-version: '11.0.11'

    - name: Build with Gradle
      run: ./gradlew assembleDebug
